# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in multiplayer.gemspec
gemspec

gem 'rake'

group :development, :test do
  gem 'rspec'
  gem 'rspec-its'
  gem 'rubocop'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'simplecov'
end
